version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 cp --recursive ./build s3://2cm.io/

      # set the cache-control headers for service-worker.js to prevent
      # browser caching
      
      # set the cache-control headers for index.html to prevent
      # browser caching
      - >
        aws s3 cp  
        --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        ./build/index.html s3://2cm.io/
artifacts:
  files:
    - '**/*'
  base-directory: build